version: "3.9"
services:
  rosenv:
    build:
      context: ./
      dockerfile: ./docker/rosenv.dockerfile
      network: host
    volumes:
      - ../:/root/workdir
      - ~/.ssh/:/root/.ssh/ # May be non-functioning in windows
      - ~/.gitconfig:/root/.gitconfig # May be non-functioning in windows
    ports:
      - 22:22 # SSH port
    tty: true # use terminal, i.e. -t flag
    stdin_open: true # allow terminal input, i.e. -i flag
    environment:
      DISPLAY: "novnc-rosenv:0.0"
    networks:
      - x11
  novnc-rosenv:
    hostname: 'novnc-rosenv'
    image: theasp/novnc:latest
    environment:
      DISPLAY_WIDTH: 5000
      DISPLAY_HEIGHT: 5000
      RUN_XTERM: "no"
      RUN_FLUXBOX: "yes"
    ports:
      - "8080:8080" # Internet port
    networks:
      - x11
networks:
  x11:
